import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import "@fontsource/lato/400.css";
import "@fontsource/lato/700.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Add Lato manually via CSS variable
const lato = { variable: "--font-lato" };

export const metadata = {
  title: {
    default: "MasWrite",
    template: "%s | MasWrite",
  },
  description: "Generated by MasWrite",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased`}
        style={{ fontFamily: 'var(--font-lato), var(--font-geist-sans), sans-serif' }}
      >
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: "#333",
              color: "#fff",
            },
          }}
        />
      </body>
    </html>
  );
}
